### ISSUE TITLE
README references incorrect path

### ISSUE THREAD

**Issue by mrwatson-de** [Saxonica/SaxonJS-Tutorial-2021#2]
Hi Norm et al,

Just trying out the tutorial and stumbled across a mistake in the README.

In the section "Compile with Java" the command to run is

`./gradlew -Pxsl=exercises/ex2/ex2.xsl eej`

However, this seems to have been written BEFORE the number of exercises increased to 10 or more and all the exercises <10 were renamed with a leading 0.

This line should be corrected to 

`./gradlew --stacktrace -Pxsl=exercises/ex02/ex02.xsl eej`

Thanks for the tutorial!

Regards from Germany

MrWatson

**Comment by mrwatson-de** [comment]
Looks like the same applies for the other systems here:

    ./gradlew -Pxsl=exercises/ex2/ex2.xsl node_xslt3
    ./gradlew -Pxsl=exercises/ex2/ex2.xsl docker_xslt3

**Comment by ndw** [comment]
Fixed, thanks!

**Comment by mrwatson-de** [comment]
Thanks
