### ISSUE TITLE
Tutorial ex.02 error: "Development license for supplied stylesheet has expired"

### ISSUE THREAD

**Issue by jvwong** [Saxonica/SaxonJS-Tutorial-2021#3]
I am working through the tutorial, running a NodeJS server. For Exercise 2 I am seeing an error:

```
Transformation failure: Error SXJS0006
    Development license for supplied stylesheet has expired
```

**Comment by jvwong** [comment]
I compiled sef.json using the nodejs package as per https://saxonica.github.io/SaxonJS-Tutorial-2021/presentation/partich12.html.

**Comment by ndw** [comment]
Sorry about that. Several of the SEF files in the repository had been compiled with the evaluation license we used during the tutorial. SEF files compiled with an evaluation license have an expiration date. I've republished those without an expiration date and updated the dependencies to run SaxonJS 2.6.
